name: Run tests on pull request
on:
  pull_request:
    branches: [ main ]
jobs:
  run-tests-on-PR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: yarn
    - run: yarn test
